### PR TITLE
Resolved undo issue#13

### PR DESCRIPTION
**Pull request by Satvinder31415**
The issue of undo was resolved by storing all previous moves instead of only the last move(as multiple undo calls could be made which was the cause of the issue).

### CODE REVIEW

**Comment by bymayanksingh** [comment]
Please test it on your end, I guess the bug still persists.

**Comment by Satvinder31415** [comment]
It works fine on my end. Any suggestions on what to do?

**Comment by bymayanksingh** [comment]
by mistake I tested master branch of yours, it's all fine just rechecked undo_resolve branch. 
I think we are good to go with this one ! 

nice and quick work @Satvinder31415 ! keep it up.

**Comment by bymayanksingh** [comment]
merging in !

**Comment by bymayanksingh** [comment]
fixes #13

**Comment by Satvinder31415** [comment]
> 
> 
> by mistake I tested master branch of yours, it's all fine just rechecked undo_resolve branch.
> I think we are good to go with this one !
> 
> nice and quick work @Satvinder31415 ! keep it up.

thx

**Pull request merged**
