### PR TITLE
Resolved issue#21

### PR DESCRIPTION
**Pull request by KomalKalyan**
Removed all my comments

### CODE REVIEW

**Comment by KomalKalyan** [comment]
I am sorry if i have sent multiple requests, just got confused

**Comment by bymayanksingh** [comment]
> I am sorry if i have sent multiple requests, just got confused

yes, multiple requests were made, we don't really need this PR, although nice work in previous one :)

**Comment by bymayanksingh** [comment]
closing this request.

**Comment by KomalKalyan** [comment]
Thank u!

**Pull request closed without merging**
