### PR TITLE
Added a test file for game_board.py

### PR DESCRIPTION
**Pull request by Satvinder31415**

### CODE REVIEW

**Comment by bymayanksingh** [comment]
can you move this to **tests** directory?

**Comment by bymayanksingh** [comment]
also this is work in progress PR right? you are working on tests for other modules too?

**Comment by Satvinder31415** [comment]
yup

**Comment by Satvinder31415** [comment]
@code-monk08 I'm having trouble importing game_board if i put the test file in a separate directory.Any suggestions on what to do?

**Comment by Satvinder31415** [comment]
nvm got it sending a pr

**Pull request closed without merging**
