### PR TITLE
Made it User Friendly

### PR DESCRIPTION
**Pull request by KomalKalyan**
Have found few errors and corrected them.
Made the start menu more interactive
And removed the restart.sh file, the game can now restart from inside game.py. \
At the end of each game, the play and quit buttons reappear.

### CODE REVIEW

**Comment by KomalKalyan** [comment]
Plz go through the changes i have made

**Comment by bymayanksingh** [comment]
Hey we have conflicting files here, please resolve them, in the mean time I will go through your pull request.

**Comment by KomalKalyan** [comment]
Sure! But will take time, I was working on this from a long time, so right
now I am going out for some work will try to resolve conflicts by tonight!
Thank u.

**Comment by KomalKalyan** [comment]
i will send without conflicts

**Comment by KomalKalyan** [comment]
Sorry to disturb you;
             I have made the start menu user interactive and made few
changes( in which restart.sh was not required) and I have put you a PR.
And also I am almost done with the player name part in which a virtual
keyboard sort of thing appears in the game window and you type the name.
But I have not put a PR, just waiting for you to accept my former PR.

KomalKalyan :)

**Pull request closed without merging**
